### ISSUE TITLE
Switch to simpler branching model ("GitHub flow")

### ISSUE THREAD

**Issue by bittner** [pytest-dev/pytest-play#56]
Congratulations, @davidemoro, for your awesome work and the transition of pytest-play to the all-time-famous - and important! - *pytest-dev* organization.

I see that the repository's branching model is obviously somewhat [git-flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow), with `develop` being the primary branch and `master` being the secondary, though - in the end - main branch. Can we switch to the simpler feature-branch based model with just a single main branch (`master`), like *pytest*? Really just asking...

P.S.: Just found a [background reading](http://endoflineblog.com/gitflow-considered-harmful) that summarizes some characteristics of git-flow. No pun intended.

**Comment by davidemoro** [comment]
Hi @bittner, thanks!

No problem, I think it would be better to switch to the same pytest branching model as you suggest

**Comment by davidemoro** [comment]
Before closing I need someone with administration rights on github: the main branch should be master now.

Can I ask your help @nicoddemus please?
Thanks in advance,

davide

**Comment by nicoddemus** [comment]
You should be able to do that yourself, let me check the settings...

**Comment by nicoddemus** [comment]
@davidemoro you are now administrator here (that was probably a slip up during the transfer). Let me know if you can change the default branch now.

**Comment by davidemoro** [comment]
Closed, thanks
